(function(){
 const app=document.getElementById('app');
 function render(){const s=QSRouter.parse();let html;
  if(s.path==='/login')html=QSViews.auth('login');else if(s.path==='/register')html=QSViews.auth('register');else if(s.path==='/reset-password')html=QSViews.auth('reset');else if(s.path==='/loading')html=QSViews.auth('loading');
  else if(s.path.startsWith('/clients'))html=QSViews.clients(s);else if(s.path==='/client/new')html=QSViews.profile(s);else if(s.path==='/client/archived')html=QSViews.profile(s,true);else if(s.path.startsWith('/client/'))html=QSViews.profile(s);else if(s.path.startsWith('/assessment/'))html=QSViews.assessment(s);else if(s.path.startsWith('/assessment-details'))html=QSViews.details(s);else if(s.path.startsWith('/report/'))html=QSViews.report(s);else if(s.path==='/trainer')html=QSViews.trainer(s);else if(s.path==='/configuration')html=QSViews.config(s);else if(s.path==='/team'||s.path==='/team/empty')html=QSViews.team(s.path==='/team/empty'||s.hash==='empty');else if(s.path==='/error')html=QSViews.system('error');else if(s.path==='/empty')html=QSViews.system('empty');else if(s.path==='/disabled')html=QSViews.system('disabled');else if(s.path==='/archived')html=QSViews.system('archived');else if(s.path==='/toast-success')html=QSUI.page('<div class="system-state"><div class="state-icon">✓</div><h1>Toast success</h1><p>Przykładowy komunikat pozytywny.</p><button class="btn btn-teal" data-action="toast" data-toast="Operacja demonstracyjna zakończona.">Pokaż toast</button></div>','clients');else if(s.path==='/toast-error')html=QSUI.page('<div class="system-state"><div class="state-icon">!</div><h1>Toast error</h1><p>Przykładowy komunikat błędu.</p><button class="btn btn-danger" data-action="toast" data-toast="Przykładowy błąd demonstracyjny." data-kind="error">Pokaż toast</button></div>','clients');else html=QSViews.clients(s);app.innerHTML=html;applyQueryState(s)}
 function applyQueryState(s){if(!s.query.modal)return;const key=s.query.modal==='new'?'new-client':s.query.modal==='edit'?'edit-client':s.query.modal;const trigger=document.querySelector(`[data-modal="${key}"]`);if(trigger&&s.path!=='/clients')trigger.click()}
 function openNavigator(){const groups=QS.nav.map(([title,links])=>`<div class="nav-group"><strong>${title}</strong>${links.map(([label,route])=>`<button class="nav-link" data-route="${route}">${label}</button>`).join('')}</div>`).join('');document.body.insertAdjacentHTML('beforeend',`<aside class="navigator"><div class="card-head"><h3>Prototype Navigator</h3><button class="close" data-action="close-navigator">×</button></div><small>Warstwa developerska · statyczne widoki</small>${groups}</aside>`)}
 function criteria(){document.body.insertAdjacentHTML('beforeend',QSUI.sheet('Kryteria: Shoulder Clearing',`<div class="stack"><div class="status-line info">i Procedura i kryteria są pokazane jako referencja trenerska.</div><div class="card"><h3>Ustawienie</h3><p>Badany stoi stabilnie. Wykonuje wzorzec górny i dolny osobno po lewej oraz prawej stronie.</p></div><div class="card"><h3>Kryteria oceny</h3><ul><li>kontrolowany zakres ruchu</li><li>brak kompensacji tułowiem</li><li>obserwacja bólu i różnicy stron</li></ul></div><button class="btn btn-primary" data-action="close-overlay">Rozumiem, wróć do testu</button></div>`))}
 function toast(text,kind){document.querySelector('.toast')?.remove();document.body.insertAdjacentHTML('beforeend',QSUI.toast(text,kind));setTimeout(()=>document.querySelector('.toast')?.remove(),2800)}
 document.addEventListener('click',e=>{const route=e.target.closest('[data-route]');if(route){e.preventDefault();QSRouter.go(route.dataset.route);return}const action=e.target.closest('[data-action]');if(!action)return;const a=action.dataset.action;if(a==='navigator'){openNavigator();return}if(a==='close-navigator'){document.querySelector('.navigator')?.remove();return}if(a==='criteria'){criteria();return}if(a==='close-overlay'||e.target.classList.contains('modal-backdrop')||e.target.classList.contains('sheet-backdrop')){document.querySelector('.modal-backdrop,.sheet-backdrop')?.remove();return}if(a==='modal'){const type=action.dataset.modal;QSRouter.go(type==='new-client'?'#/clients?modal=new':type==='edit-client'?'#/clients?modal=edit':type==='password'?'#/trainer?modal=password':type==='cert'?'#/trainer?modal=cert':'#/configuration?modal=rule');return}if(a==='select'){action.parentElement.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));action.classList.add('selected');return}if(a==='toast')toast(action.dataset.toast||'Funkcja nieaktywna w makiecie.',action.dataset.kind||'success')});
 QSRouter.init(render);
})();
