const previewRoleKey='qs-preview-role';
const roleDefinitions={
 client:{label:'Klient',route:'#/client-panel',items:[['Start','Dashboard klienta','#/client-panel','Twój podgląd postępów i wyników'],['Wyniki','Mój profil','#/client/demo','Dane profilu i historia badań'],['Wyniki','Szczegóły wyniku','#/assessment-details/demo','Pełne wyniki ostatniego badania'],['Wyniki','Raport','#/report/demo','Podgląd raportu screeningowego']],bottom:[['Start','⌂','#/client-panel'],['Profil','◉','#/client/demo'],['Wynik','◌','#/assessment-details/demo']]},
 trainer:{label:'Trener',route:'#/trainer-panel',items:[['Praca','Klienci','#/clients','Profile i historia klientów'],['Praca','Badanie','#/assessment','Rozpocznij screening ruchowy'],['Praca','Dashboard trenera','#/trainer-panel','Priorytety i aktywność workspace'],['Konto','Profil trenera','#/trainer','Dane i certyfikacje']],bottom:[['Klienci','♧','#/clients'],['Badanie','⊕','#/assessment'],['Profil','◉','#/trainer']]},
 admin:{label:'Admin',route:'#/admin-panel',items:[['Administracja','Dashboard administratora','#/admin-panel','Stan workspace i audyt'],['Administracja','Zespół i role','#/team','Członkowie oraz zaproszenia'],['Administracja','Konfiguracja','#/configuration','Testy i reguły clearingu'],['Konto','Profil trenera','#/trainer','Dane właściciela i certyfikacje']],bottom:[['Dashboard','⌂','#/admin-panel'],['Zespół','♧','#/team'],['Konfiguracja','☷','#/configuration']]},
 'trainer-admin':{label:'Trener + admin',route:'#/trainer-admin-panel',items:[['Praca','Klienci','#/clients','Profile i historia klientów'],['Praca','Badanie','#/assessment','Rozpocznij screening ruchowy'],['Praca','Dashboard łączony','#/trainer-admin-panel','Widok trenera i administratora'],['Administracja','Zespół i role','#/team','Członkowie oraz zaproszenia'],['Administracja','Konfiguracja','#/configuration','Testy i reguły clearingu'],['Konto','Profil trenera','#/trainer','Dane i certyfikacje']],bottom:[['Klienci','♧','#/clients'],['Zespół','♙','#/team'],['Konfiguracja','☷','#/configuration']]}
};
function getPreviewRole(){const saved=localStorage.getItem(previewRoleKey);if(saved&&roleDefinitions[saved])return saved;const path=location.hash.split('?')[0];if(path.includes('/client-panel'))return 'client';if(path.includes('/trainer-admin-panel'))return 'trainer-admin';if(path.includes('/admin-panel'))return 'admin';return 'trainer'}
function setPreviewRole(role){localStorage.setItem(previewRoleKey,role)}
const previousShell=QSUI.shell;
QSViews.trainerAdminPanel=function(){return QSViews.adminPanel().replace('Administracja · QuickScreen','Tryb łączony · QuickScreen').replace('Panel administratora','Panel trenera + administratora').replace('Administrator','Trener + admin')};
QSUI.shell=function(content,active='clients'){
 const role=getPreviewRole();const definition=roleDefinitions[role];const current=location.hash;
 const switcher=`<section class="preview-role-switch" aria-label="Wybór widoku makiety"><span>Podgląd jako</span><div>${Object.entries(roleDefinitions).map(([key,item])=>`<a class="${role===key?'active':''}" href="${item.route}" data-preview-role="${key}">${item.label}</a>`).join('')}</div></section>`;
 const grouped=definition.items.reduce((groups,[group,label,route,description])=>{(groups[group]??=[]).push([label,route,description]);return groups},{});
 const menu=`<details class="main-menu"><summary>Menu <span aria-hidden="true">⌄</span></summary><div class="main-menu-panel">${Object.entries(grouped).map(([title,links])=>`<div class="main-menu-group"><span>${title}</span>${links.map(([label,route,description])=>`<a class="${current.includes(route.replace('#',''))?'active':''}" href="${route}"><b>${label}</b><small>${description}</small></a>`).join('')}</div>`).join('')}</div></details>`;
 const bottom=`<nav class="bottom-nav"><div class="bottom-nav-inner">${definition.bottom.map(([label,icon,route])=>`<a class="nav-item" href="${route}"><span class="icon">${icon}</span>${label}</a>`).join('')}</div></nav>`;
 document.body.dataset.previewRole=role;
 return previousShell.call(this,content,active).replace(/<nav class="main-menu"[\s\S]*?<\/nav>/,menu).replace(/<nav class="bottom-nav"[\s\S]*?<\/nav>/,bottom).replace(/<button class="nav-fab"[\s\S]*?<\/button>/,'').replace('</header>',`</header>${switcher}`);
};
document.addEventListener('click',event=>{const control=event.target.closest('[data-preview-role]');if(control)setPreviewRole(control.dataset.previewRole)},true);
