/* Makieta konfiguracji protokołu: odczyt i formularze edycji bez zapisu danych. */
QSViews.config = function (state) {
  const typeLabel = { score: 'Punktacja 0-3', passfail: 'Pass / Fail', bilateral: 'Ocena lewej i prawej strony', shoulder: 'Test clearingowy barku', pain: 'Test bólowy' };
  const kind = state.query.kind;
  const mode = state.query.mode;
  const index = Number(state.query.item);
  const item = kind === 'test' ? QS.tests[index] : kind === 'rule' ? QS.rules[index] : null;
  const detail = !item ? '' : kind === 'test'
    ? mode === 'edit'
      ? QSUI.modal(`Edytuj: ${item.name}`, `<div class="stack"><div class="field"><label>Nazwa testu</label><input class="input" value="${item.name}"></div><div class="field"><label>Model punktacji</label><select class="select"><option selected>${typeLabel[item.type]}</option><option>Punktacja 0-3</option><option>Pass / Fail</option><option>Ocena stron</option></select></div><div class="field"><label>Instrukcja dla badanego</label><textarea class="textarea">${item.instruction}</textarea></div><button class="btn btn-primary" data-action="toast" data-toast="Zapis konfiguracji jest nieaktywny w makiecie.">Zapisz zmiany</button></div>`)
      : QSUI.modal(`Szczegóły: ${item.name}`, `<div class="protocol-detail"><span class="badge badge-info">${typeLabel[item.type]}</span><div><span class="eyebrow">Instrukcja dla badanego</span><p>${item.instruction}</p></div><div><span class="eyebrow">Jak raportować wynik</span><p>${item.type === 'bilateral' ? 'Zapisz osobno wynik lewej i prawej strony. Do wyniku końcowego przenoszony jest wynik niższy.' : item.type === 'shoulder' || item.type === 'pain' ? 'Zapisz wynik clearingu jako obecność lub brak bólu. Dodatni clearing wpływa na wynik końcowy według aktywnej reguły.' : 'Zapisz wynik zgodnie z wybranym modelem punktacji protokołu.'}</p></div><a class="btn btn-outline" href="#/configuration?kind=test&mode=edit&item=${index}">Edytuj test</a></div>`)
    : mode === 'edit'
      ? QSUI.modal(`Edytuj regułę`, `<div class="stack"><div class="field"><label>Nazwa reguły</label><input class="input" value="${item.name}"></div><div class="field"><label>Warunek</label><input class="input" value="${item.when}"></div><div class="field"><label>Efekt</label><input class="input" value="${item.effect}"></div><button class="btn btn-primary" data-action="toast" data-toast="Zapis konfiguracji jest nieaktywny w makiecie.">Zapisz zmiany</button></div>`)
      : QSUI.modal(`Szczegóły reguły`, `<div class="protocol-detail"><span class="badge ${item.active ? 'badge-pass' : 'badge-neutral'}">${item.active ? 'Aktywna' : 'Wyłączona'}</span><div><span class="eyebrow">Warunek</span><p>${item.when}</p></div><div><span class="eyebrow">Efekt w wyniku</span><p>${item.effect}</p></div><p class="muted">Reguła jest interpretowana po zebraniu odpowiedzi, przed obliczeniem końcowego wyniku i raportu.</p><a class="btn btn-outline" href="#/configuration?kind=rule&mode=edit&item=${index}">Edytuj regułę</a></div>`);

  const body = `<div class="role-dashboard protocol-config"><div class="page-head"><div><div class="eyebrow">QuickScreen · administracja</div><h1>Konfiguracja protokołu</h1><p>Testy i reguły, które określają przebieg screeningu oraz wynik końcowy.</p></div></div><section class="card"><div class="card-head"><div><span class="eyebrow">Katalog testów</span><h2>Elementy screeningu</h2></div><span class="badge badge-info">${QS.tests.length} elementów</span></div><div class="protocol-list">${QS.tests.map((test, testIndex) => `<div class="protocol-row"><div><b>${test.name}</b><small>${typeLabel[test.type]}</small></div><div class="protocol-row-actions"><a class="btn btn-ghost btn-sm" href="#/configuration?kind=test&mode=detail&item=${testIndex}">Szczegóły</a><a class="btn btn-soft btn-sm" href="#/configuration?kind=test&mode=edit&item=${testIndex}">Edytuj</a></div></div>`).join('')}</div></section><section class="card"><div class="card-head"><div><span class="eyebrow">Clearing rules</span><h2>Reguły wyniku</h2></div><span class="badge badge-info">${QS.rules.filter(rule => rule.active).length} aktywne</span></div><div class="protocol-list">${QS.rules.map((rule, ruleIndex) => `<div class="protocol-row"><div><b>${rule.name}</b><small>${rule.when} → ${rule.effect}</small></div><div class="protocol-row-actions"><a class="btn btn-ghost btn-sm" href="#/configuration?kind=rule&mode=detail&item=${ruleIndex}">Szczegóły</a><a class="btn btn-soft btn-sm" href="#/configuration?kind=rule&mode=edit&item=${ruleIndex}">Edytuj</a></div></div>`).join('')}</div></section></div>${detail}`;
  return QSViews.layout(body, 'config');
};
