/* Deterministic client-report engine based on sources/fms-report-bases-v3. */
(function(){
  var tests={
    cervical:{name:'Ruchomość szyi',order:10,short:'Zakres ruchu szyi i obecność bólu.',general:'Pokazuje, czy szyja porusza się swobodnie w podstawowych kierunkach potrzebnych na co dzień.',active:'Pokazuje, czy szyja ma wystarczającą swobodę ruchu do treningu i orientacji głowy.'},
    toe_touch:{name:'Skłon i praca bioder',order:20,short:'Skłon, praca bioder i kontrola tułowia.',general:'Pokazuje, jak swobodnie i pod kontrolą wykonujesz skłon oraz jak biodra i tułów współpracują przy pochylaniu.',active:'Pokazuje jakość podstawowego ruchu zgięcia bioder i tułowia, który pojawia się w wielu ćwiczeniach i sportach.'},
    shoulder_mobility:{name:'Mobilność obręczy barkowej',order:30,short:'Swoboda ruchu barków i współpraca z tułowiem.',general:'Pokazuje, jak swobodnie pracują barki przy sięganiu nad głowę i za plecy.',active:'Pokazuje jakość pracy barków i tułowia w ruchach nad głową i innych zadaniach kończyn górnych.'},
    squat:{name:'Przysiad',order:40,short:'Kontrola i zakres ruchu dolnej części ciała w przysiadzie.',general:'Pokazuje, jak dobrze kontrolujesz obniżenie ciała i powrót do pozycji stojącej.',active:'Pokazuje jakość podstawowego ruchu obciążania kończyn dolnych.'},
    balance:{name:'Równowaga jednonóż',order:50,short:'Równowaga, propriocepcja i kontrola jednej nogi.',general:'Pokazuje, jak pewnie kontrolujesz ciało na jednej nodze.',active:'Pokazuje podstawową kontrolę jednonóż potrzebną w biegu, lądowaniu i zadaniach asymetrycznych.'},
    rotation:{name:'Rotacja całego ciała',order:60,short:'Rotacja całego ciała i przenoszenie ciężaru.',general:'Pokazuje, jak swobodnie i pod kontrolą obracasz całe ciało oraz czy obie strony robią to podobnie.',active:'Pokazuje, jak dobrze ciało organizuje skręt i przenoszenie ciężaru.'}
  };
  var sportText={football:'W piłce nożnej ten obszar ma znaczenie przy zmianie kierunku, hamowaniu i pracy asymetrycznej.',climbing:'We wspinaniu ten ruch często pojawia się w asymetrycznych pozycjach i podczas przenoszenia ciężaru między kończynami.',badminton:'W badmintonie ten wynik ma znaczenie dla szybkiej zmiany kierunku, pracy jednonóż, rotacji i ruchów nad głową.',squash:'W squashu ten obszar jest ważny dla kontroli przy zmianach kierunku i rotacji.',athletics:'W lekkoatletyce znaczenie wyniku zależy od konkurencji — biegi mocniej wykorzystują kontrolę jednonóż, a rzuty rotację i barki.',swimming:'W pływaniu jakość tego ruchu ma znaczenie, bo jest powtarzana wiele razy.',cycling:'W kolarstwie ten sposób pracy ciała jest powtarzany przez długi czas.',triathlon:'W triathlonie ten obszar warto odnieść do połączonych wymagań pływania, kolarstwa i biegu.',martial_arts:'W sztukach walki ten ruch pojawia się podczas szybkiej zmiany pozycji, rotacji i pracy jednostronnej.'};
  function badge(state){return '<span class="report-state '+state.toLowerCase()+'"><i></i>'+state+'</span>'}
  function makeItem(id,values,pain,user,extra){
    var known=values.filter(function(v){return v!==undefined&&v!==null&&v!=='not_assessable'}),final=pain?0:(known.length?Math.min.apply(null,known):'not_assessable'),asym=known.length===2&&known[0]!==known[1]?[Math.max.apply(null,known),Math.min.apply(null,known)].join('_'):null,status=pain?'PROTECT':final===1||asym?'CORRECT':'DEVELOP',meaning;
    if(pain) meaning='Podczas tego ruchu pojawił się ból. To jest teraz ważniejsze niż sam wynik ruchowy.';
    else if(final==='not_assessable') meaning='Tego elementu nie udało się dobrze ocenić, dlatego nie wpływa na wybór głównego priorytetu.';
    else if(asym==='3_2') meaning='Obie strony radzą sobie dobrze, ale jedna wyraźnie lepiej.';
    else if(asym&&final===1) meaning='Jedna strona wyraźnie odstaje.';
    else meaning=final===1?'Wynik 1 oznacza, że ten ruch nie spełnia jeszcze podstawowego standardu dzisiejszego badania.':final===2?'Ten ruch spełnia podstawowy standard dzisiejszego badania.':'W tym ruchu spełniasz wszystkie kryteria dzisiejszego testu.';
    return Object.assign({id:id,values:values,final:final,pain:pain,asym:asym,status:status,meaning:meaning,extra:extra||'',profileMeaning:user.profile==='active'?tests[id].active:tests[id].general},tests[id]);
  }
  function build(input){
    var r=input.results,u=input.user,c=r.cervical,painNeck=[c.flexion.pain,c.rotation.right.pain,c.rotation.left.pain,c.rotation_extension.right.pain,c.rotation_extension.left.pain].indexOf('positive')>-1,failNeck=[c.flexion.rom,c.rotation.right.rom,c.rotation.left.rom].indexOf('fail')>-1,neckAsym=c.rotation.right.rom!==c.rotation.left.rom&&c.rotation.right.rom!=='not_assessable'&&c.rotation.left.rom!=='not_assessable',neckExtra=painNeck?'Ból w jednym z ruchów szyi.':failNeck?(neckAsym?'Różnica zakresu między stronami.':'Jeden z kierunków nie spełnia podstawowego zakresu.'):'Wszystkie oceniane kierunki spełniają kryteria.',shoulderPain=Object.keys(r.shoulder_clearing).some(function(k){var side=r.shoulder_clearing[k];return Object.keys(side).some(function(x){return side[x]==='positive'})});
    var items=[
      makeItem('cervical',[],painNeck,u,neckExtra),
      makeItem('toe_touch',[r.toe_touch.right.raw_score,r.toe_touch.left.raw_score],r.toe_touch.pain,u),
      makeItem('shoulder_mobility',[r.shoulder_mobility.right.raw_score,r.shoulder_mobility.left.raw_score],shoulderPain,u,shoulderPain?'Dodatni Shoulder Clearing ustawia status PROTECT.':''),
      makeItem('squat',[r.squat.score],r.squat.pain,u),
      makeItem('balance',[r.balance.right.raw_score,r.balance.left.raw_score],r.balance.pain,u),
      makeItem('rotation',[r.rotation.right.raw_score,r.rotation.left.raw_score],r.rotation.pain,u)
    ];
    if(failNeck&&!painNeck){items[0].status='CORRECT';items[0].meaning=neckAsym?'Ruch szyi różni się między stronami. Jedna strona spełnia podstawowy zakres, a druga jeszcze nie.':'Zakres ruchu szyi jest za mały w tym kierunku.'}
    if(r.spine_extension_clearing&&r.spine_extension_clearing.pain==='positive')items.push({id:'spine_extension',name:'Wyprost kręgosłupa',order:35,short:'Test bólowy.',values:[],final:0,pain:true,status:'PROTECT',meaning:'Podczas wyprostu kręgosłupa pojawił się ból.',profileMeaning:'To wymaga dokładniejszego sprawdzenia.',extra:'Test bólowy.'});
    items.sort(function(a,b){return a.order-b.order});
    var pains=items.filter(function(x){return x.pain}),corrective=items.filter(function(x){return !x.pain&&(x.final===1||x.asym||(x.id==='cervical'&&failNeck))});
    return {items:items,pains:pains,corrective:corrective,primary:pains.length?null:corrective[0]||null};
  }
  function row(x,i){
    var facts=x.values.map(function(v,n){return '<span>'+(x.values.length===2?(n?'Lewa: ':'Prawa: '):'')+(v==='not_assessable'?'nie oceniono':v+'/3')+'</span>'}).join(''),level=x.pain?'Ból / 0':x.final==='not_assessable'?'Nie oceniono':x.final+'/3';
    return '<details class="client-result '+x.status.toLowerCase()+'" '+(x.status!=='DEVELOP'?'open':'')+'><summary><span class="result-index">'+String(i+1).padStart(2,'0')+'</span><span><b>'+x.name+'</b><small>'+x.short+'</small></span>'+badge(x.status)+'<em>+</em></summary><div class="client-result-body"><div class="result-score">'+level+'</div><p>'+x.meaning+'</p><p class="result-meaning">'+x.profileMeaning+'</p>'+(facts?'<div class="result-facts">'+facts+'</div>':'')+(x.extra?'<p class="result-extra">'+x.extra+'</p>':'')+'</div></details>';
  }
  function render(input){
    var e=build(input),u=input.user,c=QS.client,lead,painNames=e.pains.map(function(x){return x.name}).join(', '),context=u.profile==='active'?sportText[u.sports[0]]||'Ten wynik warto odnieść do wymagań Twojej aktywności.':'';
    if(e.pains.length)lead={state:'PROTECT',title:e.pains.length>1?'W kilku ruchach pojawił się ból.':'Podczas ruchu pojawił się ból.',body:'To jest teraz najważniejsza informacja z badania. Na razie nie dokładaj większego obciążenia, zakresu ani intensywności w obszarach: '+painNames+'. Najpierw warto sprawdzić je dokładniej.'};
    else if(e.primary)lead={state:'CORRECT',title:'Najważniejszy obszar do pracy: '+e.primary.name,body:e.primary.meaning+' '+e.primary.profileMeaning+' '+context+' Najpierw popraw podstawową jakość tego ruchu, potem zwiększaj wymagania.'};
    else lead={state:'DEVELOP',title:'Nie ma dziś jednego wyraźnego problemu do poprawy.',body:'Wszystkie oceniane ruchy osiągają co najmniej dobry, podstawowy poziom. Możesz dalej rozwijać jakość, siłę i kontrolę tych ruchów.'};
    var history=u.previous_completed_screens_count>0?'<section class="client-report-section change-section"><div class="section-kicker">02 / ZMIANA W CZASIE</div><h2>Co zmieniło się od poprzedniego badania</h2><div class="change-note"><b>Poprzedni priorytet</b><span>'+input.previous.primary+'</span><i>→</i><b>Obecnie</b><span>'+(e.pains.length?'Ból podczas ruchu':e.primary?e.primary.name:'Brak wyraźnego priorytetu')+'</span></div><p>Historia porównuje konkretne ruchy, nie tylko wynik łączny. Ten raport pokazuje aktualny punkt wyjścia do kolejnej rozmowy.</p></section>':'';
    var other=e.corrective.filter(function(x){return x!==e.primary}).slice(0,3),strong=e.items.filter(function(x){return x.status==='DEVELOP'&&(x.final===2||x.final===3)}).slice(0,3),state=!u.account_exists?'<section class="report-cta"><b>Wiesz już, gdzie zacząć.</b><p>Chcesz przełożyć ten wynik na konkretny plan pracy? Odezwij się do mnie.</p><button class="btn btn-teal">Skontaktuj się</button></section>':u.previous_completed_screens_count?'<section class="report-cta"><b>Najważniejsze jest to, co zmienia się w czasie.</b><p>Przy kolejnym badaniu sprawdzimy, co poprawiło się i na czym warto skupić się dalej.</p></section>':'<section class="report-cta"><b>To jest Twój punkt wyjścia.</b><p>Kolejne badanie pokaże, co się zmieniło.</p></section>';
    var body='<main class="report-page report-v3"><div class="report-actions"><a class="btn btn-ghost btn-sm" href="#/client/demo">← Profil klienta</a><div><button class="btn btn-outline btn-sm" onclick="window.print()">Drukuj</button><button class="btn btn-teal btn-sm" data-action="toast" data-toast="Eksport PDF jest dostępny z widoku druku.">Pobierz PDF</button></div></div><article class="report-document"><header class="report-v3-head"><div class="report-mark">KB<span>+</span></div><div><span>RAPORT BADANIA RUCHOWEGO</span><h1>'+c.name+'</h1><p>'+input.screen.date+' · '+c.discipline+' · '+input.screen.id+'</p></div><div class="report-author"><small>PRZYGOTOWAŁ</small><b>'+QS.trainer.name+'</b><span>QuickScreen v2</span></div></header><section class="report-lead-v3 '+lead.state.toLowerCase()+'"><div class="lead-signal">'+badge(lead.state)+'<span>'+(e.pains.length||e.corrective.length||e.items.length)+'<small>obserwacji</small></span></div><div><span class="section-kicker">NAJWAŻNIEJSZE TERAZ</span><h2>'+lead.title+'</h2><p>'+lead.body+'</p></div></section>'+history+'<section class="client-report-section"><div class="section-kicker">'+(u.previous_completed_screens_count>0?'03':'02')+' / WYNIKI</div><h2>Co zobaczyliśmy dzisiaj</h2><p class="section-intro">Najpierw znaczenie wyniku, potem szczegóły techniczne.</p><div class="client-results">'+e.items.map(row).join('')+'</div></section>'+(other.length?'<section class="client-report-section supporting-section"><div class="section-kicker">KOLEJNE OBSERWACJE</div><h2>Nie musisz poprawiać wszystkiego naraz</h2><div class="support-grid">'+other.map(function(x){return '<article><b>'+x.name+'</b><p>'+x.meaning+'</p></article>'}).join('')+'</div></section>':'')+(strong.length?'<section class="client-report-section strengths-section"><div class="section-kicker">MOCNE STRONY</div><h2>To możesz normalnie rozwijać</h2><p>Wyniki 2 i 3 spełniają podstawowy standard dzisiejszego badania.</p><div>'+strong.map(function(x){return '<span>'+x.name+' <b>'+x.final+'/3</b></span>'}).join('')+'</div></section>':'')+state+'<footer class="report-v3-footer"><div><b>Move well. Move often.</b><span>Najpierw jakość, potem więcej obciążenia, szybkości i złożoności.</span></div><p>Badanie ma charakter przesiewowy. Pokazuje, które obszary warto poprawić lub sprawdzić dokładniej, ale nie określa przyczyny bólu ani ograniczenia.</p></footer></article></main>';
    return QSViews.layout(body,'report');
  }
  window.QSReports={build:build}; QSViews.report=function(){return render(QS.reportDemo)};
}());
