/* Client-first report. Technical score mechanics remain available, but never lead the reading order. */
QSViews.report = function () {
  const client=QS.client, history=QS.history, latest=history[0], previous=history[1], change=previous?latest.score-previous.score:null;
  const badge=(kind,label)=>`<span class="report-status ${kind}"><i>${kind==='pass'?'✓':'!'}</i>${label}</span>`;
  const results=[
    {name:'Cervical Flexion',kind:'pass',state:'Bez dodatkowych uwag',meaning:'Zakres i reakcję bólową oceniono prawidłowo.',facts:['Zakres ruchu: Pass','Ból: brak bólu']},
    {name:'Cervical Rotation and Extension',kind:'pain',state:'Do omówienia',meaning:'Sam zakres jest prawidłowy, ale clearing szyi wskazał ból po prawej stronie.',facts:['Lewa strona: Pass · brak bólu','Prawa strona: Pass · brak bólu'],clearing:{name:'Neck Extension Clearing',summary:'Ból po prawej stronie',facts:['Lewa strona: brak bólu','Prawa strona: ból','Wynik clearingu: Fail · ból']}},
    {name:'Toe Touch',kind:'attention',state:'Do obserwacji',meaning:'Widoczna jest różnica stron; warto porównać ją przy kolejnym badaniu.',facts:['Lewa strona: 1/3','Prawa strona: 2/3','Ocena końcowa: 1/3 (niższa strona)']},
    {name:'Shoulder Mobility',kind:'pain',state:'Do omówienia',meaning:'Ból w clearingu barku zmienił końcową ocenę mobilności barku.',facts:['Lewa strona: 1/3','Prawa strona: 2/3','Ocena przed clearingiem: 1/3'],clearing:{name:'Shoulder Clearing',summary:'Ból po prawej stronie wpływa na wynik',facts:['Wzorzec górny: L brak bólu / P ból','Wzorzec dolny: L brak bólu / P ból','Ocena po clearingu: 0/3']}},
    {name:'Rotation',kind:'pain',state:'Do omówienia',meaning:'Wynik wskazuje ból po lewej stronie i różnicę między stronami.',facts:['Lewa strona: 0/3 · ból','Prawa strona: 1/3','Ocena końcowa: 0/3']},
    {name:'Balance',kind:'attention',state:'Do obserwacji',meaning:'Różnica stron jest informacją do pracy i porównania przy retescie.',facts:['Lewa strona: 1/3','Prawa strona: 2/3','Ocena końcowa: 1/3 (niższa strona)']},
    {name:'Squat',kind:'pain',state:'Do omówienia',meaning:'Ocena przysiadu wymaga rozmowy w kontekście całego badania.',facts:['Ocena końcowa: 0/3'],clearing:{name:'Spine Extension Clearing',summary:'Brak bólu w clearingu',facts:['Wynik testu: brak bólu']}}
  ];
  const resultCards=results.map((item,index)=>`<details class="report-result-card ${item.kind}" ${item.kind!=='pass'?'open':''}><summary><span class="report-result-number">${String(index+1).padStart(2,'0')}</span><div><h3>${item.name}</h3><p>${item.meaning}</p></div>${badge(item.kind,item.state)}<i class="report-result-toggle">+</i></summary><div class="report-result-details"><div class="report-facts">${item.facts.map(fact=>`<span>${fact}</span>`).join('')}</div>${item.clearing?`<div class="report-clearing-detail"><div><small>TEST POWIĄZANY · CLEARING</small><b>${item.clearing.name}</b><p>${item.clearing.summary}</p></div><div>${item.clearing.facts.map(fact=>`<span>${fact}</span>`).join('')}</div></div>`:''}</div></details>`).join('');
  const priorities=results.filter(item=>item.kind!=='pass').slice(0,3).map((item,index)=>`<article class="report-priority-card ${item.kind}"><span>${String(index+1).padStart(2,'0')}</span><div><small>${index===0?'GŁÓWNY PRIORYTET':index===1?'KOLEJNY OBSZAR':'DO OBSERWACJI'}</small><h3>${item.name}</h3><p>${item.meaning}</p></div></article>`).join('');
  return QSViews.layout(`<div class="report-page report-universal"><div class="report-actions"><a class="btn btn-ghost btn-sm" href="#/client-panel">← Panel klienta</a><span>Widok raportu</span><div><button class="btn btn-outline btn-sm" onclick="window.print()">Drukuj</button><button class="btn btn-teal btn-sm" data-action="toast" data-toast="Eksport PDF jest reprezentowany przez widok druku.">Pobierz PDF</button></div></div><article class="report-paper">
<header class="universal-report-head"><span class="report-client-avatar">${client.initials}</span><div><span class="eyebrow">RAPORT BADANIA</span><h1>${client.name}</h1><p>QuickScreen v2 · ${latest.date} · ${client.discipline}</p></div><div class="report-assessment-id"><small>NUMER BADANIA</small><b>QS-2026-0907</b><span>Karol Bilecki</span></div></header>
<section class="report-context-strip"><div><small>AKTYWNOŚĆ</small><b>${client.discipline}</b></div><div><small>CEL BADANIA</small><b>Ocena aktualnego wzorca ruchu</b></div><div><small>PROWADZĄCY</small><b>Karol Bilecki</b></div></section>
<section class="report-now-card"><div class="report-score-current"><small>OBRAZ AKTUALNY</small><strong>${latest.score}<em>/15</em></strong>${badge('pain','Wymaga omówienia')}</div><div><small>NAJWAŻNIEJSZE TERAZ</small><h2>Najpierw: wynik barku</h2><p>W clearingu barku pojawił się ból po prawej stronie. Omów go z trenerem przed doborem ćwiczeń i obciążeń.</p><div class="report-micro-stats"><span><b>3</b> obszary do obserwacji</span><span><b>3</b> sygnały bólu</span><span><b>${change>0?'+':''}${change??'—'}</b> pkt od ostatniego</span></div></div></section>
<section class="report-section"><header class="universal-section-title"><div><span class="eyebrow">01 · AKTUALNY OBRAZ</span><h2>Wyniki, które łatwo zrozumieć</h2></div><p>Najpierw znaczenie wyniku; szczegóły techniczne po rozwinięciu.</p></header><div class="report-results-map">${resultCards}</div></section>
<section class="report-section"><header class="universal-section-title"><div><span class="eyebrow">02 · PRIORYTETY</span><h2>Na czym warto skupić się teraz?</h2></div></header><div class="report-priorities">${priorities}<article class="report-priority-card pass"><span>+</span><div><small>MOCNY ELEMENT</small><h3>Cervical Flexion</h3><p>Zakres i brak bólu — ten wynik warto utrzymać.</p></div></article></div></section>
<section class="report-section"><header class="universal-section-title"><div><span class="eyebrow">03 · PROGRES</span><h2>Zmiana od ostatniego badania</h2></div></header><div class="report-progress"><div class="report-change"><small>ZMIANA WYNIKU ŁĄCZNEGO</small><strong>${change>0?'+':''}${change}<em> pkt</em></strong><p>${change<0?'Wynik niższy od poprzedniego badania.':'Poprawa względem poprzedniego badania.'}</p></div><div class="report-history-chart">${history.slice().reverse().map(item=>`<div style="--score:${item.score/15*100}%"><b>${item.score}</b><i></i><small>${item.date.slice(0,5)}</small></div>`).join('')}</div></div></section>
<section class="report-section"><header class="universal-section-title"><div><span class="eyebrow">04 · NASTĘPNY KROK</span><h2>Co robimy dalej?</h2></div></header><div class="report-next-steps"><article><small>KIERUNEK PRACY</small><h3>Rozmowa o wynikach z bólem</h3><p>Nie tworzymy automatycznego planu ćwiczeń przy aktywnej fladze bólu.</p></article><article><small>RETEST</small><h3>Za 4–6 tygodni</h3><p>Cel: ponownie porównać strony i wynik clearingów.</p></article><article><small>KOMENTARZ TRENERA</small><h3>Do uzupełnienia</h3><p>Uwagi po rozmowie z klientem.</p></article></div></section>
<details class="report-disclosure"><summary><span><small>05 · INFORMACJA O BADANIU</small><b>Jak działa QuickScreen?</b></span><i>+</i></summary><p>QuickScreen obejmuje ocenę szyi, Toe Touch, barku, rotacji, równowagi i przysiadu. Wyniki stron oraz testy clearingowe mogą zmienić wynik końcowy powiązanego testu. Raport nie rozpoznaje urazu ani nie określa przyczyny problemu.</p></details><details class="report-disclosure report-technical"><summary><span><small>SZCZEGÓŁY TECHNICZNE</small><b>Skala, strony i metodologia</b></span><i>+</i></summary><div class="report-score-legend"><span><b>0–3</b> wynik skali</span><span><b>L / P</b> strony oceniane osobno</span><span><b>Pass / Fail</b> zakres lub clearing</span><span><b>ból</b> flaga wpływająca na wynik</span></div></details><footer class="report-trainer-signature"><span>KB</span><div><small>RAPORT PRZYGOTOWAŁ</small><h3>Karol Bilecki</h3><p>Trener przygotowania motorycznego · QuickScreen<br>info@kbtrener.pl</p></div><p>Raport informacyjny, nie diagnoza medyczna.</p></footer>
</article></div>`,'report');
};
