import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const input = resolve(
  root,
  "FMS_Quick_Screen_Codex_Package/config/quick_screen_seed.json",
);
const output = resolve(root, "apps-script/00_Seed.js");
const seed = JSON.parse(readFileSync(input, "utf8"));
const banner = [
  "// Generated by npm run build:seed. Do not edit by hand.",
  "// Source: FMS_Quick_Screen_Codex_Package/config/quick_screen_seed.json",
  "var FMS_SEED = " + JSON.stringify(seed, null, 2) + ";",
  "",
].join("\n");

writeFileSync(output, banner, "utf8");
console.log("Generated apps-script/00_Seed.js");
