import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const input = resolve(
  root,
  "FMS_Quick_Screen_Codex_Package/config/quick_screen_seed.json",
);
const output = resolve(root, "apps-script/00_Seed.js");
const manualOutput = resolve(root, "apps-script/08_ManualCriteria.js");
const seed = JSON.parse(readFileSync(input, "utf8"));
const banner = [
  "// Generated by npm run build:seed. Do not edit by hand.",
  "// Source: FMS_Quick_Screen_Codex_Package/config/quick_screen_seed.json",
  "var FMS_SEED = " + JSON.stringify(seed, null, 2) + ";",
  "",
].join("\n");

writeFileSync(output, banner, "utf8");
const manualPath = resolve(root, "08_manual_criteria_and_report_text.md");
const manualSource = readFileSync(manualPath, "utf8");
writeFileSync(manualOutput, [
  "// Generated by npm run build:seed from the owner-provided manual criteria.",
  "var FMS_MANUAL_SOURCE = " + JSON.stringify(manualSource) + ";",
  "var FmsManual = (function () {",
  "  var headings = { cervical_flexion: 1, cervical_rotation_extension: 2, toe_touch: 3, shoulder_mobility: 4, shoulder_clearing: 5, rotation: 6, balance: 7, squat: 8, spine_extension_clearing: 9 };",
  "  function section(code) {",
  "    var number = headings[code]; if (!number) return \"\";",
  String.raw`    var match = FMS_MANUAL_SOURCE.match(new RegExp("^## " + number + "\\. [^\\n]+\\n([\\s\\S]*?)(?=^## \\d+\\. |$)", "m"));`,
  "    return match ? match[1].trim() : \"\";",
  "  }",
  "  function all() { var result = {}; Object.keys(headings).forEach(function (code) { result[code] = section(code); }); return result; }",
  "  function common() { var marker = FMS_MANUAL_SOURCE.indexOf('## 1. '); return marker < 0 ? FMS_MANUAL_SOURCE : FMS_MANUAL_SOURCE.slice(0, marker).trim(); }",
  "  return { section: section, all: all, common: common };",
  "})();",
  "",
].join("\n"), "utf8");
console.log("Generated apps-script/00_Seed.js");
