const COLORS={primary:'#0F172A',muted:'#64748B',line:'#E2E8F0',surface:'#F1F5F9',secondary:'#0D9488',pass:'#059669',passBg:'#ECFDF5',attention:'#D97706',attentionBg:'#FFFBEB',pain:'#E11D48',painBg:'#FFF1F2'};
const has=(data,code)=>data.enabledSections.includes(code);
const statusColors=level=>level==='pain'?[COLORS.pain,COLORS.painBg]:level==='attention'?[COLORS.attention,COLORS.attentionBg]:[COLORS.pass,COLORS.passBg];
const testFacts=item=>{const facts=[];if(item.rawScores?.left!=null)facts.push(`Lewa: ${item.rawScores.left}`);if(item.rawScores?.right!=null)facts.push(`Prawa: ${item.rawScores.right}`);if(item.finalScore!=null)facts.push(`Wynik końcowy: ${item.finalScore}`);for(const answer of item.answers||[])facts.push(`${answer.side==='left'?'L · ':answer.side==='right'?'P · ':''}${answer.field}: ${answer.value}`);return[...new Set(facts)]};

function testCard(item,showDescription){const[color,background]=statusColors(item.status.level),middle=[];if(item.photos?.[0]?.dataUrl)middle.push({image:item.photos[0].dataUrl,width:96,margin:[0,3,10,3]});if(showDescription)middle.push({text:item.description,fontSize:7.5,color:'#475569',margin:[0,4,0,2]});return{unbreakable:true,margin:[0,0,0,5],table:{widths:[4,'*'],body:[[{text:'',fillColor:color,border:[false,false,false,false]},{stack:[{columns:[{text:`${item.index}. ${item.name}`,font:'Outfit',fontSize:10.5,bold:true},{text:item.finalScore==null?item.status.label:`Wynik: ${item.finalScore} - ${item.status.label}`,alignment:'right',fontSize:7.5,bold:true,color,fillColor:background,margin:[4,1,4,1]}]},...(middle.length?[{columns:middle,columnGap:5}]:[]),{text:testFacts(item).join('   |   ')||'Wynik opisowy',fontSize:7,color:'#334155',margin:[0,3,0,0]},...(item.asymmetry?[{text:'! Asymetria stron',fontSize:7.5,bold:true,color:COLORS.attention,margin:[0,3,0,0]}]:[]),...(item.note?[{text:[{text:'Notatka trenera: ',bold:true},item.note],fontSize:7.5,fillColor:'#F0FDFA',margin:[0,3,0,0]}]:[])],margin:[8,6,8,6],border:[false,false,false,false]}]]},layout:{hLineColor:()=>COLORS.line,vLineColor:()=>COLORS.line,paddingLeft:()=>0,paddingRight:()=>0,paddingTop:()=>0,paddingBottom:()=>0}}}

export function createFmsPdfDefinition(data){const pain=data.priorityFindings.filter(x=>x.severity==='pain').length,asymmetry=data.priorityFindings.filter(x=>x.type==='asymmetry').length,low=data.priorityFindings.filter(x=>x.type==='score_1').length,discipline=data.clientDisciplines.map(x=>x.discipline).join(', ')||'Nie podano',certification=data.trainerCertifications.map(x=>x.name).join(', ')||'Trener FMS',heading=text=>({text,font:'Outfit',fontSize:13,bold:true,color:COLORS.primary,margin:[0,11,0,6],headlineLevel:2}),content=[{columns:[{image:data.logoData,width:82,margin:[0,-18,10,-20]},{width:'*',stack:[{text:'FMS STANDARD',fontSize:7,bold:true,color:'#FFFFFF',background:COLORS.primary,margin:[0,0,0,3]},{text:'RAPORT SCREENINGU RUCHOWEGO FMS',font:'Outfit',fontSize:16,bold:true},{text:'Karta wyników badania motorycznego i biomechanicznego',fontSize:7.5,color:COLORS.muted}]},{width:110,stack:[{text:'TRENER PROWADZĄCY',style:'metaLabel',alignment:'right'},{text:data.trainer.name,fontSize:8.5,bold:true,alignment:'right'},{text:certification,fontSize:7,color:COLORS.secondary,alignment:'right'}]}],columnGap:8,margin:[0,0,0,8]},{table:{widths:['*','*','*','*'],body:[[{stack:[{text:'IMIĘ I NAZWISKO',style:'metaLabel'},{text:`${data.client.firstName} ${data.client.lastName}`,bold:true}]},{stack:[{text:'ADRES E-MAIL',style:'metaLabel'},{text:data.client.email}]},{stack:[{text:'DYSCYPLINA',style:'metaLabel'},{text:discipline}]},{stack:[{text:'DATA BADANIA',style:'metaLabel'},{text:data.latest.assessmentDate,bold:true}]}]]},layout:{fillColor:()=>COLORS.surface,hLineColor:()=>COLORS.line,vLineColor:()=>COLORS.line},margin:[0,0,0,8]}];
  if(has(data,'executive_summary'))content.push({table:{widths:[150,'*'],body:[[{stack:[{text:'WYNIK ŁĄCZNY',style:'metaLabel'},{text:[{text:String(data.latest.totalScreenScore),font:'Outfit',fontSize:32,bold:true},{text:' / 15 pkt',fontSize:11,color:COLORS.muted}],margin:[0,5,0,5]},{text:pain?'! Wymaga konsultacji':low||asymmetry?'! Wymaga uwagi':'OK W normie',fontSize:8,bold:true,color:pain?COLORS.pain:low||asymmetry?COLORS.attention:COLORS.pass}]},{stack:[{text:'ZIDENTYFIKOWANE CZYNNIKI RYZYKA',font:'Outfit',fontSize:10,bold:true,margin:[0,0,0,6]},{columns:[{stack:[{text:'Ból / red flag',bold:true,color:COLORS.pain},{text:`${pain} obserwacji`,fontSize:8}],fillColor:COLORS.painBg,margin:[6,5]},{stack:[{text:'Asymetrie',bold:true,color:COLORS.attention},{text:`${asymmetry} prób`,fontSize:8}],fillColor:COLORS.attentionBg,margin:[6,5]},{stack:[{text:'Wyniki obniżone',bold:true,color:COLORS.attention},{text:`${low} wzorców`,fontSize:8}],fillColor:COLORS.attentionBg,margin:[6,5]}],columnGap:5}]}]]},layout:{hLineColor:()=>COLORS.line,vLineColor:()=>COLORS.line},margin:[0,0,0,7]},{text:'Skala FMS:   0 - ból / red flag     1 - ograniczenie lub asymetria     2-3 - wynik prawidłowy',fontSize:7.5,color:'#475569',margin:[6,2,0,11]});
  content.push({stack:[{text:'OPIS METODOLOGII I CELU BADANIA',style:'metaLabel'},{text:'FMS QuickScreen jest standaryzowanym screeningiem podstawowych wzorców ruchowych. Wynik porządkuje obserwacje dotyczące bólu, asymetrii, ograniczeń i kompensacji.',fontSize:8.5}],fillColor:COLORS.surface,margin:[8,7,8,9]});
  if(has(data,'latest_assessment'))content.push(heading(`Zestawienie szczegółowe prób ruchowych (${data.latest.assessmentDate})`),...data.testItems.map(item=>testCard(item,has(data,'test_descriptions'))));
  if(has(data,'priority_findings'))content.push(heading('Priorytetowe obserwacje'),...(data.priorityFindings.length?data.priorityFindings.map(item=>({text:[{text:`${item.severity==='pain'?'!':'△'} ${item.title}: `,bold:true},item.detail],fontSize:8.5,fillColor:item.severity==='pain'?COLORS.painBg:COLORS.attentionBg,margin:[7,5,7,5],unbreakable:true})):[{text:'Nie zarejestrowano priorytetowych flag.',fontSize:8}]));
  if(has(data,'history')){const matrix=[[{text:'Test',bold:true},...data.assessments.map(a=>({text:a.assessmentDate,bold:true}))],...data.numericTests.map(test=>[test.name,...data.assessments.map(a=>`${Object.keys(a.rawScores[test.code]).length>1?`L ${a.rawScores[test.code].left} / P ${a.rawScores[test.code].right} -> `:''}${a.finalScores[test.code]}`)])];content.push(heading('Historia wyników'),{table:{headerRows:1,widths:['auto',...data.assessments.map(()=>'*')],body:matrix},layout:'lightHorizontalLines',fontSize:7,dontBreakRows:true})}
  if(has(data,'recommendations'))content.push(heading('Zalecenia trenera'),...data.recommendations.map(item=>({stack:[{text:item.tests?.name||item.category,bold:true},{text:item.content},{text:[item.frequency,item.duration].filter(Boolean).join(' · '),fontSize:7,color:COLORS.muted}],fillColor:'#F8FAFC',margin:[7,5],unbreakable:true})));
  content.push(heading('Metodologia i wersje'),{text:`Manual: ${data.manualVersion||'brak wersji'} · Generator: ${data.generatorVersion} · Profil: ${data.reportProfile}`,fontSize:7.5,color:'#475569'});if(has(data,'trainer_signature'))content.push({columns:[{text:`${data.trainer.name}\nTrener prowadzący`,margin:[0,10,0,0]},{text:'Data i podpis',alignment:'right',margin:[0,10,0,0]}],fontSize:8});content.push({text:'Raport opisuje zapisane wyniki screeningu i nie stanowi diagnozy ani zalecenia terapeutycznego.',fontSize:7,color:COLORS.muted,margin:[0,8,0,0]});
  return{info:{title:`FMS Quick Screen - ${data.client.firstName} ${data.client.lastName}`},pageSize:'A4',pageMargins:[34,34,34,38],defaultStyle:{font:'Inter',fontSize:8.5,color:COLORS.primary},styles:{metaLabel:{fontSize:6.5,bold:true,color:COLORS.muted,margin:[0,0,0,3]}},content,footer:(page,pages)=>({columns:[{text:`FMS QuickScreen · ${data.client.firstName} ${data.client.lastName}`,margin:[34,0,0,0]},{text:`Strona ${page} / ${pages}`,alignment:'right',margin:[0,0,34,0]}],fontSize:7,color:COLORS.muted})};
}
